# Generated by Django 5.2.14 on 2026-05-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web'), ('research_software', 'Research software'), ('ai_data', 'AI and data'), ('automation', 'Automation'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived'), ('experimental', 'Experimental')], max_length=16)),
                ('problem_context', models.TextField(blank=True)),
                ('technical_approach', models.TextField(blank=True)),
                ('role', models.CharField(max_length=255)),
                ('tech_stack', models.TextField(help_text='Comma-separated technologies or short stack description.')),
                ('repository_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
