# Generated by Django 5.2.14 on 2026-06-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/visual-evidence/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Describe the project image for accessibility.', max_length=255),
        ),
    ]
